python3 -u train.py \
  --batch_size 64 \
  --protein_vocab protein_vocab.model \
  --nmr_dir /media/DATA/meson324/hmdb_fid_files_unzipped \
  --log_interval 100 \
  --epoch 30 \
  --lr 0.0001 \
  --train_file_name /media/DATA/meson324/dataset/ibm3/train \
  --valid_file_name /media/DATA/meson324/dataset/ibm3/valid \
  --test /media/DATA/meson324/dataset/ibm3/test \
  --concat_model concat \
  --protein_model att w\
  --chemical_model att \
  --chemical_embedding_size 64 \
  --protein_embedding_size 64 \
  --sequential_hidden_size 64 \
  --transformer_model_dim 256 \
  --transformer_hidden_dimension 256 \
  --transformer_num_layers 12